name: Meilensteine | Web

on:
  push:
    paths: 
      - 'packages/web/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      working-directory: packages/web
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: build version
      id: version
      uses: ./.github/actions/build-version
      with:
        package-path: packages/web/package.json
    - name: output version
      run: |
        echo "Using version: ${{steps.version.outputs.version}} for Docker"
    - name: Build image
        run: docker build . --file Dockerfile --tag meilensteine-web
     - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
    - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/meilensteine-web
          VERSION=${{steps.version.outputs.version}}

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag meilensteine-web $IMAGE_ID:$VERSION

          docker push $IMAGE_ID:$VERSION

