name: Meilensteine | Web

on:
  push:
    paths: 
      - 'packages/web/*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm install, build, and test
      working-directory: packages/web
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: build version
      id: version
      uses: ./.github/actions/build-version
      with:
        package-path: packages/web/package.json
    - name: output version
      run: echo "${{steps.version.version}}"

